"""empty message

Revision ID: 66b275b81ac9
Revises: 743066481575
Create Date: 2021-05-08 17:15:24.511887

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66b275b81ac9'
down_revision = '743066481575'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('seat',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('booker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booker_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('movie', sa.Column('Booker_id', sa.Integer(), nullable=True))
    op.add_column('movie', sa.Column('content', sa.Text(), nullable=False))
    op.add_column('movie', sa.Column('create_time', sa.DateTime(), nullable=True))
    op.add_column('movie', sa.Column('title', sa.String(length=100), nullable=False))
    op.create_foreign_key(None, 'movie', 'user', ['Booker_id'], ['id'])
    op.drop_column('movie', 'moviename')
    op.drop_column('movie', 'country')
    op.drop_column('movie', 'genre')
    op.drop_column('movie', 'year')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('year', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('movie', sa.Column('genre', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('movie', sa.Column('country', mysql.VARCHAR(length=100), nullable=False))
    op.add_column('movie', sa.Column('moviename', mysql.VARCHAR(length=100), nullable=False))
    op.drop_constraint(None, 'movie', type_='foreignkey')
    op.drop_column('movie', 'title')
    op.drop_column('movie', 'create_time')
    op.drop_column('movie', 'content')
    op.drop_column('movie', 'Booker_id')
    op.drop_table('seat')
    # ### end Alembic commands ###
