"""empty message

Revision ID: 743066481575
Revises: cc3a39a25b6e
Create Date: 2021-04-28 10:00:54.940216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '743066481575'
down_revision = 'cc3a39a25b6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('year', sa.Integer(), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'year')
    # ### end Alembic commands ###
