"""empty message

Revision ID: 78498814eadd
Revises: b625036a95b6
Create Date: 2021-05-08 17:27:47.982130

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78498814eadd'
down_revision = 'b625036a95b6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('hall',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('create_time', sa.DateTime(), nullable=True),
    sa.Column('movie_id', sa.Integer(), nullable=True),
    sa.Column('booker_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['booker_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('hall')
    # ### end Alembic commands ###
