"""empty message

Revision ID: b625036a95b6
Revises: 66b275b81ac9
Create Date: 2021-05-08 17:17:51.161980

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b625036a95b6'
down_revision = '66b275b81ac9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('movie', sa.Column('comment', sa.Text(), nullable=False))
    op.add_column('movie', sa.Column('genre', sa.String(length=100), nullable=False))
    op.add_column('movie', sa.Column('year', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('movie', 'year')
    op.drop_column('movie', 'genre')
    op.drop_column('movie', 'comment')
    # ### end Alembic commands ###
