"""empty message

Revision ID: e7e96323e471
Revises: 78498814eadd
Create Date: 2021-05-08 17:29:04.187051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7e96323e471'
down_revision = '78498814eadd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('seat', sa.Column('hall_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'seat', 'hall', ['hall_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'seat', type_='foreignkey')
    op.drop_column('seat', 'hall_id')
    # ### end Alembic commands ###
